CubeSummation/Models/CubeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CubeSummation.Models
{
    public class CubeModel
    {
        public CubeModel() { }

        public long x0 { get; set; }
        public long y0 { get; set; }
        public long z0 { get; set; }
        public long x { get; set; }
        public long y { get; set; }
        public long z { get; set; }
        public long value { get; set; }
        public int section { get; set; }

    }

}

CubeSummation/Models/CubeSummationModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CubeSummation.Models
{
    public class CubeSummationModel
    {

        [Display(Name = "Casos de prueba")]
      ///  [Required(ErrorMessage = "El campo Aoc es requerido")]
        public int Cprueba { get; set; } 

        [Display(Name = "Dimension Matriz")]
     ///[Required(ErrorMessage = "El campo Nombre es requerido")]
        public int Dimension { get; set; }

        [Display(Name = "# Operaciones")]
        public int NOperacion { get; set; }

        [Display(Name = "Tipo de operacion")]
        public string TOperacion { get; set; }

        [Display(Name = "Coordenada x")]
        public int x  { get; set; }

        [Display(Name = "Coordenada y")]
        public int y { get; set; }

        [Display(Name = "Coordenada z")]
        public int z { get; set; }

        [Display(Name = "Coordenada x0")]
        public int x0 { get; set; }

        [Display(Name = "Coordenada y0")]
        public int y0 { get; set; }

        [Display(Name = "Coordenada z0")]
        public int z0 { get; set; }

        [Display(Name = "value")]
        public long value { get; set; }

        [Display(Name = "section")]
        public int section { get; set; }
    }
}

CubeSummation/Models/MatrizModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CubeSummation.Models
{
    public class MatrizModel
    {
        public long[,,] Matrix { get; set; }
    }
}

CubeSummation/Controllers/CubeSummationController.cs
using CubeSummation.BussinesLogic;
using CubeSummation.Models;
using System;
using System.Web.Mvc;

namespace CubeSummation.Controllers
{

    public class CubeSummationController : Controller
    {
        CubeSummationProcess bussinesLogicCube = new CubeSummationProcess();
        long resultProcess = 0;

        // GET: CubeSummation
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AjaxUpdate(CubeSummationModel cubeModelData)
        {
            CubeModel cubeModel = new CubeModel
            {
                x = cubeModelData.x,
                y = cubeModelData.y,
                z = cubeModelData.z,
                value = cubeModelData.value,
                section = cubeModelData.section
            };

            resultProcess = bussinesLogicCube.Process(cubeModelData.Dimension, cubeModelData.NOperacion, cubeModelData.TOperacion, cubeModel);
            return Json(resultProcess, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AjaxSearch(CubeSummationModel cubeModelData)
        {
            CubeModel cubeModel = new CubeModel
            {
                x = cubeModelData.x,
                y = cubeModelData.y,
                z = cubeModelData.z,
                x0 = cubeModelData.x0,
                y0 = cubeModelData.y0,
                z0 = cubeModelData.z0,
                section = cubeModelData.section
            };

            resultProcess = bussinesLogicCube.Process(cubeModelData.Dimension, cubeModelData.NOperacion, cubeModelData.TOperacion, cubeModel);
            return Json(resultProcess, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AjaxCleanMatrix(int section)
        {
            resultProcess = 0;
            if (bussinesLogicCube.CleanSectionMatriz(section)) resultProcess = 1;
            return Json(resultProcess, JsonRequestBehavior.AllowGet);
        }

        private ActionResult agregar()
        {
            return View(2);
        }
    }
}

CubeSummation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CubeSummation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CubeSummation/Views/CubeSummation/Index.cshtml
@model CubeSummation.Models.CubeSummationModel

@{
    ViewBag.Title = "Index";
   //int Cprueba = 0;
}

@*<h2>Index</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2>Cube Summation Model</h2>
    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Cprueba, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cprueba, new { htmlAttributes = new { @class = "form-control ", @min = "1", @max = "5" } })
            @Html.ValidationMessageFor(model => model.Cprueba, "", new { @class = "text-danger" })
        </div>
    </div>
   
    <div class="alert alert-danger" role="alert" id="alertError">
    </div>
    <div id="Result" class="form-group">
    </div>

    @*@if (Cprueba != 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Dimension, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Dimension, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Dimension, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NOperacion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NOperacion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NOperacion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TOperacion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TOperacion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TOperacion, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.x, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.x, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.x, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.y, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.y, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.y, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.z, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.z, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.z, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.x1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.x1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.x1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.y1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.y1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.y1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.z1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.z1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.z1, "", new { @class = "text-danger" })
                </div>
            </div>
        }*@
    @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>*@
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
}

CubeSummation/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CubeSummation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CubeSummation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

    <div class="jumbotron">
        <h1>Cube Summation</h1>
        <p class="lead">La aplicación fue desarrollada para evidenciar los comportamientos de un Cubo Multidimensional, .</p>
        <p>@Html.ActionLink("Ver Aquí", "Index", "CubeSummation", null, new {@class = "btn btn-primary btn-lg"})</p>
    </div>

<div class="row">
    @*<div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>*@
</div>

CubeSummation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Cube", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cube Summation", "Index", "CubeSummation")</li>
                    @*<li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>